sudo: required
before_install:
  - sudo gem install cocoapods
language: swift
osx_image: xcode7.2
xcode_workspace: TLDR.xcworkspace
xcode_scheme: TLDR
xcode_sdk: iphonesimulator9.0

branches:
  only:
    - master
